name: human_project_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  avatar_glow:
  animated_text_kit:
  page_transition: ^1.1.4
  bouncing_widget: ^1.2.0
  delayed_display: ^1.0.2
  liquid_swipe: ^1.3.1
  badges: ^1.1.0
  story_view:
  dots_indicator: ^1.0.0
  settings_ui: ^0.2.0
  material_about: ^0.2.1
  material_design_icons_flutter: ^2.7.94
  url_launcher:  ^5.2.1
  provider: ^3.1.0
  flutter_launch:
  share_it:
  flutter_open_whatsapp:


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - Assets/img/don_de_sang.jpg
      - Assets/img/loved.png
      - Assets/img_isaac.jpg
      - Assets/img/bd.png
      - Assets/undraw2.png
      - Assets/undraw3.png
      - Assets/undraw5.png
      - Assets/undraw7.png
      - Assets/loginScreen.jpg
      - Assets/loginScreen2.jpg
      - Assets/loginScreen3.jpg
      - Assets/img_maps.jpg
      - Assets/img/img1.jpg
      - Assets/img/img2.jpg
      - Assets/img/img3.jpg
      - Assets/img/img4.jpg
      - Assets/img/img5.jpg
      - Assets/img/img6.jpg
      - Assets/img/img8.jpg
      - Assets/img/img9.jpg
      - Assets/img/woman.jpg
      - Assets/img/img10.jpg
      - Assets/intro1.jpg


      - Assets/img_ong/img1.jpg
      - Assets/img_ong/img2.jpg
      - Assets/img_ong/img3.jpg
      - Assets/img_ong/img4.jpg
      - Assets/img_ong/img5.jpg
      - Assets/img_ong/img6.jpg
      - Assets/img_ong/img7.jpg
      - Assets/img_ong/img8.jpg
      - Assets/img_ong/img9.jpg
      - Assets/img_ong/img10.jpg

      - Assets/img_statut/img1.jpg
      - Assets/img_statut/img2.jpg
      - Assets/img_statut/img3.jpg
      - Assets/img_statut/img4.jpg
      - Assets/img_statut/img5.jpg
      - Assets/img_statut/img6.jpg
      - Assets/img_statut/img7.jpg
      - Assets/img_statut/img8.jpg
      - Assets/img_statut/img9.jpg
      - Assets/img_statut/img10.jpg

      - Assets/img_profil_statut/img1.jpg
      - Assets/img_profil_statut/img2.jpg
      - Assets/img_profil_statut/img3.jpg
      - Assets/img_profil_statut/img4.jpg
      - Assets/img_profil_statut/img5.jpg
      - Assets/img_profil_statut/img6.jpg
      - Assets/img_profil_statut/img7.jpg
      - Assets/img_profil_statut/img8.jpg
      - Assets/img_profil_statut/img9.jpg
      - Assets/img_profil_statut/img10.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
          - asset: Assets/fonts/Montserrat-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Releway
       fonts:
         - asset: Assets/fonts/Raleway-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
